/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vertsequer
 */
public class RH_Inicio extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos;
    Thread hilo;
    int x, y;
    public static String nombre;
    public static String depto;

    /**
     * Creates new form menu
     */
    public RH_Inicio() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(51, 102, 255));
        fecha();
         pnlMenu.setBackground(new Color(0,153,255, 130));
        pnlrelog.setBackground(new Color(0, 0, 0, 130));
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        //alineacion de los label con el nombre y  departamento 
        lblnombrerh.setHorizontalAlignment(lblnombrerh.CENTER);
        lblnombrerh.setVerticalAlignment(lblnombrerh.CENTER);
        lblcargo.setHorizontalAlignment(lblcargo.CENTER);
        lblcargo.setVerticalAlignment(lblcargo.CENTER);
        //mostrar el menu minimizado 
        Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btnMenu);
        Animacion.Animacion.mover_izquierda(5, -250, 2, 2, pnlMenu);
        Animacion.Animacion.mover_izquierda(5, -250, 2, 2, lblfondomenu);
    }

    public void fecha() {
        Date fechaHoy = new Date();
        SimpleDateFormat formatoEsMX = new SimpleDateFormat(
                "d/MMMM/yyyy", new Locale("ES", "MX"));
        String[] parts = formatoEsMX.format(fechaHoy).split("/");
        String dia = parts[0];
        String mes = parts[1];
        String anio = parts[2];
        lbldia.setText(dia);
        lblmes.setText(mes);
        lblaño.setText(anio);
    }
//calse para visuaalizar la hora en tiempo real 
    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }//fin de clase hora 
    
//ejecutar el reloj
    public void run() {
        //while
        Thread current = Thread.currentThread();
        while (current == hilo) {
            hora();
            txthora.setText(hora + ":" + minutos + ":" + segundos);
        }
    }//fin 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnincidencias = new javax.swing.JButton();
        btnlistado = new javax.swing.JButton();
        btnpercepsiones = new javax.swing.JButton();
        btnnuevasinc = new javax.swing.JButton();
        btnusuarios = new javax.swing.JButton();
        btnsininc = new javax.swing.JButton();
        btnusuarioconin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblnombrerh = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlrelog = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblaño = new javax.swing.JLabel();
        lbldia = new javax.swing.JLabel();
        lblmes = new javax.swing.JLabel();
        logozunfeld = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblfondomenu = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/menublue.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 50, 50));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setCornerSize(25);
        dropShadowBorder1.setShowBottomShadow(false);
        pnlMenu.setBorder(dropShadowBorder1);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/logoZunfeld.png"))); // NOI18N

        btnincidencias.setBackground(new java.awt.Color(169, 223, 191));
        btnincidencias.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnincidencias.setText("Incidencias");
        btnincidencias.setBorder(null);
        btnincidencias.setContentAreaFilled(false);
        btnincidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnincidencias.setOpaque(true);
        btnincidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincidenciasActionPerformed(evt);
            }
        });

        btnlistado.setBackground(new java.awt.Color(0, 153, 204));
        btnlistado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnlistado.setText("Listado Personal");
        btnlistado.setBorder(null);
        btnlistado.setContentAreaFilled(false);
        btnlistado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlistado.setOpaque(true);
        btnlistado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistadoActionPerformed(evt);
            }
        });

        btnpercepsiones.setBackground(new java.awt.Color(0, 153, 204));
        btnpercepsiones.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnpercepsiones.setText("Persepciones y deducciones");
        btnpercepsiones.setBorder(null);
        btnpercepsiones.setContentAreaFilled(false);
        btnpercepsiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpercepsiones.setOpaque(true);
        btnpercepsiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpercepsionesActionPerformed(evt);
            }
        });

        btnnuevasinc.setBackground(new java.awt.Color(169, 223, 191));
        btnnuevasinc.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnnuevasinc.setText("Nuevas Persepciones");
        btnnuevasinc.setBorder(null);
        btnnuevasinc.setContentAreaFilled(false);
        btnnuevasinc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnuevasinc.setOpaque(true);
        btnnuevasinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevasincActionPerformed(evt);
            }
        });

        btnusuarios.setBackground(new java.awt.Color(169, 223, 191));
        btnusuarios.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnusuarios.setText("Usuarios");
        btnusuarios.setBorder(null);
        btnusuarios.setContentAreaFilled(false);
        btnusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusuarios.setOpaque(true);
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        btnsininc.setBackground(new java.awt.Color(169, 223, 191));
        btnsininc.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnsininc.setText("Usuarios sin Incidencias");
        btnsininc.setBorder(null);
        btnsininc.setContentAreaFilled(false);
        btnsininc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsininc.setOpaque(true);
        btnsininc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinincActionPerformed(evt);
            }
        });

        btnusuarioconin.setBackground(new java.awt.Color(0, 153, 204));
        btnusuarioconin.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnusuarioconin.setText("Usuarios con Incidencias");
        btnusuarioconin.setBorder(null);
        btnusuarioconin.setContentAreaFilled(false);
        btnusuarioconin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusuarioconin.setOpaque(true);
        btnusuarioconin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuarioconinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(btnusuarioconin, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
            .addComponent(btnnuevasinc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlistado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnsininc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnpercepsiones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnincidencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnincidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlistado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnuevasinc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpercepsiones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnusuarioconin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsininc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 53, 210, 490));

        jPanel1.setBackground(new java.awt.Color(229, 230, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/portafolio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/user.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/minimizar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 32, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/error.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 32, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/regresar.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 32, 30));

        lblnombrerh.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblnombrerh.setForeground(new java.awt.Color(51, 102, 255));
        lblnombrerh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 102, 255)));
        jPanel1.add(lblnombrerh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, 20));

        lblcargo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblcargo.setForeground(new java.awt.Color(51, 102, 255));
        lblcargo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 102, 255)));
        jPanel1.add(lblcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 200, 20));

        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 52));

        pnlrelog.setBackground(new java.awt.Color(0, 24, 96));
        pnlrelog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");
        pnlrelog.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("de");
        pnlrelog.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 40, 40));

        lblaño.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        lblaño.setForeground(new java.awt.Color(255, 255, 255));
        pnlrelog.add(lblaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 140, 60));

        lbldia.setBackground(new java.awt.Color(255, 255, 255));
        lbldia.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        lbldia.setForeground(new java.awt.Color(255, 255, 255));
        pnlrelog.add(lbldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, 70));

        lblmes.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblmes.setForeground(new java.awt.Color(255, 255, 255));
        pnlrelog.add(lblmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, 50));

        logozunfeld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/logoZunfeld.png"))); // NOI18N
        pnlrelog.add(logozunfeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 170, 80));

        txthora.setEditable(false);
        txthora.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        txthora.setAutoscrolls(false);
        txthora.setBorder(null);
        txthora.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txthora.setEnabled(false);
        pnlrelog.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 140, 50));

        getContentPane().add(pnlrelog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/fondoredesrh.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 490));

        lblfondomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/background-1634817_960_720.jpg"))); // NOI18N
        getContentPane().add(lblfondomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//minimizar la ventana 
        this.setExtendedState(ICONIFIED);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//regresar a ventana anterior 
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        menuopciones us = new menuopciones();
        us.show(true);
        menuopciones.lblcargo.setText(dep);
        menuopciones.lblnombrerh.setText(nom);
        this.show(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
     //movilizacion de la ventana con un jlabel
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
     //animacion para el menu de opciones
        int posicion = btnMenu.getX();
        if (posicion > 5) {
            Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btnMenu);
            Animacion.Animacion.mover_izquierda(5, -250, 2, 2, pnlMenu);
            Animacion.Animacion.mover_izquierda(5, -250, 2, 2, lblfondomenu);
        } else {
            Animacion.Animacion.mover_derecha(5, 200, 2, 2, btnMenu);
            Animacion.Animacion.mover_derecha(-200, 1, 2, 2, pnlMenu);
            Animacion.Animacion.mover_derecha(-230, 1, 2, 2, lblfondomenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnincidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincidenciasActionPerformed
//apartado de registro de incidencias
        RH_Incidencias inc = new RH_Incidencias();
        RH_Incidencias.lblnombrerh.setText(lblnombrerh.getText());
        RH_Incidencias.lblcargo.setText(lblcargo.getText());
        nombre = RH_Inicio.lblnombrerh.getText();
        depto = RH_Inicio.lblcargo.getText();
        inc.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnincidenciasActionPerformed

    private void btnlistadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistadoActionPerformed
    //btn listado del personal
        String dep = lblcargo.getText();
          String nom = lblnombrerh.getText();

          try {
              RH_ListadoPersonal lis = new RH_ListadoPersonal();
              lis.show();
              RH_ListadoPersonal.lblcargo.setText(dep);
              RH_ListadoPersonal.lblnombrerh.setText(nom);
              this.show(false);
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
          }        
    }//GEN-LAST:event_btnlistadoActionPerformed

    private void btnnuevasincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevasincActionPerformed
///btn para acceder al crear persepciones y deducciones
        try {
            RH_NewPercepciones inc = new RH_NewPercepciones();
            RH_NewPercepciones.lblnombrerh.setText(lblnombrerh.getText());
            RH_NewPercepciones.lblcargo.setText(lblcargo.getText());
            nombre = RH_Inicio.lblnombrerh.getText();
            depto = RH_Inicio.lblcargo.getText();
            inc.setVisible(true);
            this.setVisible(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevasincActionPerformed

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
//btn entrar a registro de ususario y asignacion de usuarios
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        RH_registrarusrs usur = new RH_registrarusrs();
        RH_registrarusrs.lblnomjefe.setText(nom);
        RH_registrarusrs.lbldepjefe.setText(dep);
        usur.show();
        this.show(false);   // TODO add your handling code here:
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btnpercepsionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpercepsionesActionPerformed
//btnm para entrar a percepciones y deducciones 
      try {
            RH_PercepcionesDeducciones per = new RH_PercepcionesDeducciones();
            per.show();
            RH_PercepcionesDeducciones.lblcargo.setText(lblcargo.getText());
            RH_PercepcionesDeducciones.lblnombrerh.setText(lblnombrerh.getText());
            this.show(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnpercepsionesActionPerformed

    private void btnusuarioconinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuarioconinActionPerformed
//btn entrar a usuarios con incidencias
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        try {
            RH_UsuariosConIncidencias usu = new RH_UsuariosConIncidencias();
            usu.show();
            RH_UsuariosConIncidencias.lblcargo.setText(dep);
            RH_UsuariosConIncidencias.lblnombrerh.setText(nom);
            this.show(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnusuarioconinActionPerformed

    private void btnsinincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinincActionPerformed
   // btn para entrar a usuarios sin incidencias
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        try {
            RH_UsuariosSinIncidencias usu = new RH_UsuariosSinIncidencias();
            usu.show();
            RH_UsuariosSinIncidencias.lblcargo.setText(dep);
            RH_UsuariosSinIncidencias.lblnombrerh.setText(nom);
            this.show(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btnsinincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RH_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnincidencias;
    private javax.swing.JButton btnlistado;
    private javax.swing.JButton btnnuevasinc;
    private javax.swing.JButton btnpercepsiones;
    private javax.swing.JButton btnsininc;
    private javax.swing.JButton btnusuarioconin;
    private javax.swing.JButton btnusuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblaño;
    public static javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lbldia;
    private javax.swing.JLabel lblfondomenu;
    private javax.swing.JLabel lblmes;
    public static javax.swing.JLabel lblnombrerh;
    private javax.swing.JLabel logozunfeld;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlrelog;
    private javax.swing.JTextField txthora;
    // End of variables declaration//GEN-END:variables
}
