/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import BD.Nomincidencia;
import Conexion.Conexion;
import Controller.Rincidencia;
import java.awt.Color;
import static java.lang.Math.E;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class RH_Incidencias extends javax.swing.JFrame {

    public static String nombre = "";
    public static String cargo = "";
//variable del modelo de la tabla de registros 
    DefaultTableModel modeloincidencias = new DefaultTableModel(null, getColums());
    //variable del filtro 
    private TableRowSorter trsFiltro;
    //variables para la conexion a la base de datos
    private PreparedStatement st;
    public static ResultSet rs;
    private Connection userConn;
    Conexion con = new Conexion();
    Connection conn;
    PreparedStatement stmt;
    Nomincidencia nom;

    public RH_Incidencias() {
        nom = new Nomincidencia();
        modeloincidencias = new DefaultTableModel(null, getColums());
       //cargar  datos al abrir la ventana
        SetFilas();
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(51, 102, 255));

    }
//clase columnas para el modelo de la tabla

    private String[] getColums() {
        String columna[] = {"Clave", "Nombre", "Estatus"};
        return columna;

    }//fin de la clase
    //mostrar registros de la tabl a incidencias en el modelo de la tabla 

    private void SetFilas() {
        try {
            String sql = "select idNomIncidencia, nombre,estatus from nomIncidencia";
            conn = (this.userConn != null) ? this.userConn : Conexion.getConnection();
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            Object datos[] = new Object[3];
            while (rs.next()) {
                for (int i = 0; i < 3; i++) {
                    datos[0] = rs.getString("idNomIncidencia");
                    datos[1] = rs.getString("nombre");
                    int est = rs.getInt("estatus");
                    if (est == 1) {
                        datos[2] = "Activo";
                    } else {
                        datos[2] = "Inactivo";
                    }
                }
                modeloincidencias.addRow(datos);
            }
//                        tabla1.addRow(datos);
        } catch (Exception e) {
            System.out.println("" + e);
        } finally {
            Conexion.close(rs);
            Conexion.close(stmt);
        }
    }//fin clase vista de registros modelo tabla 
    //clase para  limpiar la tabla 

    public void limpiar(DefaultTableModel tabla) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            i -= 1;
        }
    }//fin clase para limpiar la tabla

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asci = new javax.swing.JPopupMenu();
        actinc = new javax.swing.JMenuItem();
        desci = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblnombrerh = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblincidencias = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelreginc = new javax.swing.JPanel();
        GuardarIn = new javax.swing.JButton();
        txtdias = new javax.swing.JTextField();
        txtNomIncidencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        actinc.setText("Activar");
        actinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actincActionPerformed(evt);
            }
        });
        asci.add(actinc);

        desci.setText("Desactivar");
        desci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desciActionPerformed(evt);
            }
        });
        asci.add(desci);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 230, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/minimizar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 32, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/error.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 32, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/regresar.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 32, 30));

        lblnombrerh.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblnombrerh.setForeground(new java.awt.Color(51, 102, 255));
        lblnombrerh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 102, 255)));
        jPanel1.add(lblnombrerh, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 250, 20));

        lblcargo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblcargo.setForeground(new java.awt.Color(51, 102, 255));
        lblcargo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 102, 255)));
        jPanel1.add(lblcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 210, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/user.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/portafolio.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 52));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro Incidencias");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 186, 30));

        tblincidencias= new javax.swing.JTable(){
            public boolean  isCellEditable(int rowIndex,int conlIndex ){
                return false;
            }
        };
        tblincidencias.setAutoCreateRowSorter(true);
        tblincidencias.setForeground(new java.awt.Color(51, 51, 51));
        tblincidencias.setModel(modeloincidencias);
        tblincidencias.setComponentPopupMenu(asci);
        tblincidencias.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        tblincidencias.setFillsViewportHeight(true);
        tblincidencias.setGridColor(new java.awt.Color(255, 255, 255));
        tblincidencias.setInheritsPopupMenu(true);
        tblincidencias.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tblincidencias.setSelectionBackground(new java.awt.Color(108, 180, 221));
        tblincidencias.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tblincidencias);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 650, 230));

        txtBuscar.setBackground(new java.awt.Color(51, 102, 255));
        txtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/search1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 40, 40));

        panelreginc.setBackground(new java.awt.Color(51, 102, 255));
        panelreginc.setForeground(new java.awt.Color(255, 255, 255));

        GuardarIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/save1.png"))); // NOI18N
        GuardarIn.setContentAreaFilled(false);
        GuardarIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarInActionPerformed(evt);
            }
        });

        txtdias.setBackground(new java.awt.Color(51, 102, 255));
        txtdias.setForeground(new java.awt.Color(255, 255, 255));
        txtdias.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        txtNomIncidencia.setBackground(new java.awt.Color(51, 102, 255));
        txtNomIncidencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNomIncidencia.setForeground(new java.awt.Color(255, 255, 255));
        txtNomIncidencia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNomIncidencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomIncidenciaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Incidencia");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dias de duracion de  incidencia");

        javax.swing.GroupLayout panelregincLayout = new javax.swing.GroupLayout(panelreginc);
        panelreginc.setLayout(panelregincLayout);
        panelregincLayout.setHorizontalGroup(
            panelregincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelregincLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelregincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(panelregincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelregincLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelregincLayout.createSequentialGroup()
                        .addComponent(txtdias, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(GuardarIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        panelregincLayout.setVerticalGroup(
            panelregincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelregincLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelregincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelregincLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelregincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuardarIn)
                            .addComponent(txtdias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelregincLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        getContentPane().add(panelreginc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 650, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //boton salir 
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //boton para minimizar la ventana
        this.setExtendedState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //boton para regresar a ventana anterior
        cargo = RH_Inicio.depto;
        nombre = RH_Inicio.nombre;
        RH_Inicio rh_i = new RH_Inicio();
        rh_i.setVisible(true);
        RH_Inicio.lblcargo.setText(cargo);
        RH_Inicio.lblnombrerh.setText(nombre);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void actincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actincActionPerformed
        //activar incidencias 
        int fila = tblincidencias.getSelectedRow();
        int estatus = 0;
        if (fila >= 0) {
            String cod = tblincidencias.getValueAt(fila, 0).toString();
            String status = tblincidencias.getValueAt(fila, 2).toString();

            try {
                nom.Activar(cod);
                limpiar(modeloincidencias);
                SetFilas();
                JOptionPane.showMessageDialog(null, "Incidencia Desactivada");
            } catch (SQLException ex) {
                Logger.getLogger(RH_Incidencias.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione una fila ");
        }
    }//GEN-LAST:event_actincActionPerformed

    private void desciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desciActionPerformed
        //desactivar incidencia
        int fila = tblincidencias.getSelectedRow();
        int estatus = 0;
        if (fila >= 0) {
            String cod = tblincidencias.getValueAt(fila, 0).toString();
            String status = tblincidencias.getValueAt(fila, 2).toString();
            try {
                nom.Desactivar(cod);
                limpiar(modeloincidencias);
                SetFilas();
                JOptionPane.showMessageDialog(null, "Incidencia Desactivada");

            } catch (SQLException ex) {
                Logger.getLogger(RH_Incidencias.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione una fila ");
        }
    }//GEN-LAST:event_desciActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        //txtfield para buscar registros dentro del modelo de la tabla
        limpiar(modeloincidencias);
        String cadenaBusqueda = txtBuscar.getText();

        ArrayList<Rincidencia> listarIncidencias = nom.obteneriIncidenciaPorCriterio(cadenaBusqueda);

        int numeroProductos = listarIncidencias.size();

        modeloincidencias.setNumRows(numeroProductos);

        for (int i = 0; i < numeroProductos; i++) {
            Rincidencia inc = listarIncidencias.get(i);
            int clave = inc.getIdNomIncidencia();
            String nombre = inc.getIncidencia();
            int estatus = inc.getEstatus();
            String estatu;
            if (estatus == 1) {
                estatu = "Activo";
            } else {
                estatu = "Inactivo";

            }

            modeloincidencias.setValueAt(clave, i, 0);
            modeloincidencias.setValueAt(nombre, i, 1);
            modeloincidencias.setValueAt(estatu, i, 2);

        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void GuardarInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarInActionPerformed
        //guardar  registro de incidencias nuevas
        String NomIncidencia = txtNomIncidencia.getText();
        int dias = Integer.parseInt(txtdias.getText());
        if (NomIncidencia.equals("")) {
            JOptionPane.showMessageDialog(null, "El campo esta vacio", "", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                //llamar funcion insertar incidencias nuevas 
                nom.insert(NomIncidencia, dias);
                //limpar txt del nombre de la incidenca
                txtNomIncidencia.setText("");
                //limpiar el modelo de la tabla
                limpiar(modeloincidencias);
                //cargar filas de los datos en la tabal
                SetFilas();
            } catch (SQLException ex) {
                Logger.getLogger(RH_Incidencias.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_GuardarInActionPerformed

    private void txtNomIncidenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomIncidenciaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomIncidenciaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RH_Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RH_Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RH_Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RH_Incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RH_Incidencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarIn;
    private javax.swing.JMenuItem actinc;
    private javax.swing.JPopupMenu asci;
    private javax.swing.JMenuItem desci;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lblcargo;
    public static javax.swing.JLabel lblnombrerh;
    private javax.swing.JPanel panelreginc;
    private javax.swing.JTable tblincidencias;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNomIncidencia;
    private javax.swing.JTextField txtdias;
    // End of variables declaration//GEN-END:variables
}
